version: '3.7'

volumes:
    logs:
        driver: local

services:
    db:
        image: mysql:5.7
        # command:  --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=ALLOW_INVALID_DATES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        volumes:
            - ./db_data:/var/lib/mysql
            - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress

    server:
        depends_on:
            - db
        image: node:12-alpine
        working_dir: /app
        command: npx nodemon src/server
        environment:
            docker: "true"
            PORT: 8000
        ports:
            - 8000:8000
        volumes:
            - ./nodejs:/app

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8888:80
        environment:
        - PMA_HOST=db
        - PMA_ARBITRARY=1