version: '3.7'

volumes:
    logs:
        driver: local

services:
    db:
        image: mysql:5.7
        command: --sql_mode=ALLOW_INVALID_DATES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress

    server:
        depends_on:
            - db
        image: node:12-alpine
        working_dir: /app
        command: npx nodemon src/server
        environment:
            docker: "true"
            PORT: 8000
        ports:
            - 8000:8000
        volumes:
            - ./nodejs:/app
